### PR TITLE
Reveiw documents

### PR DESCRIPTION
**Pull request by BasheerL**
Bonjour Olivier,

I manage a couple of things for now (experiments and anonymization_privac).
I revised some writing, added some explanations, and left some comments for you @olivierabz .

I will try to do the rest tomorrow and/or beginning of next week.

Cheers
BK

### CODE REVIEW

**Comment by b-rodrigues** [comment]
Ideally, this would need to be merged after https://github.com/octopize/octopize-linkage/pull/33

**Comment by olivierabz** [comment]
I have integrated most suggestions. Note that I chose not to add the subtitles "Graph x" because they are not referenced in the text and managing the numbering manually is not practical.

**Comment by b-rodrigues** [comment]
looks like hard wrapping was removed I'll add it back in a new PR

**Comment by olivierabz** [comment]
I resolved conflicts from gh. Is hard wrapping performed through a linter ? If so, we just need to re-run it.

**Comment by b-rodrigues** [comment]
opened #34 to deal with this

**Comment by BasheerL** [comment]
[like]  Basheer Kalash reacted to your message:
________________________________

**Pull request merged**
