### PR TITLE
Add a top-level default.nix with the environment

### PR DESCRIPTION
**Pull request by b-rodrigues**
This PR adds a default.nix that defines the development environment. It builds successfully, but it would require more extensive testing to make sure that it can be used. Running `python run_use_case_pra.py` resulted in an error, but I don’t know if it’s an issue with the nix environment or if there is an error in the script itself.

The default.nix uses my fork of nixpkgs as I had to package saiph, octopize_avatar and gower which weren’t packaged for Nix. I’ll open PRs to get these packages in. If and when they’re in upstream, I’ll amend the default.nix to use upstream nixpkgs again.

### CODE REVIEW

**Comment by b-rodrigues** [comment]
@alex-l637 and @BasheerL fyi

**Comment by BasheerL** [comment]
Hi Olivier,

It is on our to do list, can we come back to you shortly on that?
@Alemayehu ***@***.***> might ping you later today if possible 😊

Thanks
Basheer


Basheer Kalash, PhD
Senior Data Scientist
Luxembourg National Data Service
6, avenue des Hauts-Fourneaux
L-4362 Esch-sur-Alzette
www.lnds.lu<https://www.lnds.lu/>
M: (+352) 621 289 134

T:  (+352) 260 207 | ***@***.******@***.***>
R.C.S. C175  | TVA LU34458768

This email (and any attachment) may contain information that is internal or confidential. If you are not the intended recipient, please inform the sender by reply and delete all copies. 


From: olivierabz ***@***.***>
Date: Thursday, 31 October 2024 at 10:50
To: octopize/octopize-linkage ***@***.***>
Cc: Basheer Kalash ***@***.***>, Mention ***@***.***>
Subject: Re: [octopize/octopize-linkage] Add a top-level default.nix with the environment (PR #19)

@alex-l637<https://github.com/alex-l637> and @BasheerL<https://github.com/BasheerL> fyi

Does it runs without issue on your machine ? If so, I merge.

Oops, I edited instead of commenting... anyway, question is the same :)

@alex-l637<https://github.com/alex-l637> and @BasheerL<https://github.com/BasheerL> fyi
Does it runs without issue on your machine ? If so, I merge

**Comment by alex-l637** [comment]
Hi, @olivierabz @b-rodrigues @BasheerL, `nix` works fine for me-- it successfully unpacks the dependencies without error, unlike poetry. 

But as @b-rodrigues commented above, I get some other errors that seem unrelated to the dependencies. 
Like: `FileNotFoundError: [Errno 2] No such file or directory: 'data/pra_A_unshuffled_avatars.csv'` 

@olivierabz, if you think this error is expected, please go ahead with merging!

**Comment by BasheerL** [comment]
[like]  Basheer Kalash reacted to your message:
________________________________

**Pull request merged**
